version: '3.8'

services:
  mysql:
    user: root
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Admin@123"
      MYSQL_DATABASE: "TestDB"
    ports:
      - "3306:3306"
    volumes:
      - ./RoboticsContainer.Infrastructure/Docker/SqlConfiguration/sql-scripts:/docker-entrypoint-initdb.d/
      # Store the MySQL data outside of your project folder to avoid conflicts
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  ntp-server:
    build:
      context: ./RoboticsContainer.Infrastructure/Docker/NtpConfiguration
    container_name: ntp-server
    ports:
      - "123:123/udp"
    restart: unless-stopped

  redis:
    build:
      context: ./RoboticsContainer.Infrastructure/Docker/RedisConfiguration
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
