services:

  mssql:
    user: root
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Admin@123"
      MSSQL_PID: "Developer"
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
    volumes:
      - ./RoboticsContainer.Infrastructure/Docker/SqlConfiguration/sql-scripts:/sql-scripts
      - ./RoboticsContainer.Infrastructure/Docker/SqlConfiguration/data:/var/opt/mssql/data
      - ./RoboticsContainer.Infrastructure/Docker/SqlConfiguration/log:/var/opt/mssql/log
      - ./RoboticsContainer.Infrastructure/Docker/SqlConfiguration/secrets:/var/opt/mssql/secrets
    restart: unless-stopped

  ntp-server:
    build:
      context: ./RoboticsContainer.Infrastructure/Docker/NtpConfiguration
    container_name: ntp-server
    ports:
      - "123:123/udp"
    restart: unless-stopped

  redis:
    build:
      context: ./RoboticsContainer.Infrastructure/Docker/RedisConfiguration
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
